// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.20.3
// source: agent/proto/agent.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_ADD         TaskType = 1
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_ADD",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_ADD":         1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_agent_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_agent_proto_agent_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_agent_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      TaskType               `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3,enum=agent.v1.TaskType" json:"task_type,omitempty"`
	Sum           int64                  `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_agent_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *AddResponse) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_agent_proto_agent_proto protoreflect.FileDescriptor

const file_agent_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x17agent/proto/agent.proto\x12\bagent.v1\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\"P\n" +
	"\vAddResponse\x12/\n" +
	"\ttask_type\x18\x01 \x01(\x0e2\x12.agent.v1.TaskTypeR\btaskType\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x03R\x03sum*8\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTASK_TYPE_ADD\x10\x012B\n" +
	"\fAgentService\x122\n" +
	"\x03Add\x12\x14.agent.v1.AddRequest\x1a\x15.agent.v1.AddResponseB\"Z ququchat/agent/pkg/grpcpb;grpcpbb\x06proto3"

var (
	file_agent_proto_agent_proto_rawDescOnce sync.Once
	file_agent_proto_agent_proto_rawDescData []byte
)

func file_agent_proto_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_agent_proto_rawDesc), len(file_agent_proto_agent_proto_rawDesc)))
	})
	return file_agent_proto_agent_proto_rawDescData
}

var file_agent_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_proto_agent_proto_goTypes = []any{
	(TaskType)(0),       // 0: agent.v1.TaskType
	(*AddRequest)(nil),  // 1: agent.v1.AddRequest
	(*AddResponse)(nil), // 2: agent.v1.AddResponse
}
var file_agent_proto_agent_proto_depIdxs = []int32{
	0, // 0: agent.v1.AddResponse.task_type:type_name -> agent.v1.TaskType
	1, // 1: agent.v1.AgentService.Add:input_type -> agent.v1.AddRequest
	2, // 2: agent.v1.AgentService.Add:output_type -> agent.v1.AddResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_proto_agent_proto_init() }
func file_agent_proto_agent_proto_init() {
	if File_agent_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_agent_proto_rawDesc), len(file_agent_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_agent_proto_msgTypes,
	}.Build()
	File_agent_proto_agent_proto = out.File
	file_agent_proto_agent_proto_goTypes = nil
	file_agent_proto_agent_proto_depIdxs = nil
}
